INSERT INTO `[DB_PREFIX]fields` (`id`, `parent_id`, `parent_type`, `section`, `field_key`, `type`, `is_core`, `is_edit`, `is_required`, `params`, `status`, `order`, `created_at`, `updated_at`, `deleted_at`) VALUES
(4, 0, 'booking', 'item', 'baby_seat', 'number_spin', 1, 0, 0, '{\"label\":\"\",\"placeholder\":\"\",\"help\":\"\",\"name\":\"\",\"is_override\":\"0\",\"is_price\":\"1\",\"trans_key\":\"baby_seats\"}', '1', '0', '2018-10-11 20:00:00', NULL, NULL),
(5, 0, 'booking', 'item', 'child_seat', 'number_spin', 1, 0, 0, '{\"label\":\"\",\"placeholder\":\"\",\"help\":\"\",\"name\":\"\",\"is_override\":\"0\",\"is_price\":\"1\",\"trans_key\":\"child_seats\"}', '1', '0', '2018-10-11 20:00:00', NULL, NULL),
(6, 0, 'booking', 'item', 'infant_seat', 'number_spin', 1, 0, 0, '{\"label\":\"\",\"placeholder\":\"\",\"help\":\"\",\"name\":\"\",\"is_override\":\"0\",\"is_price\":\"1\",\"trans_key\":\"infant_seats\"}', '1', '0', '2018-10-11 20:00:00', NULL, NULL),
(10, 0, 'booking', 'item', 'waiting_time', 'text', 1, 0, 0, '{\"label\":\"\",\"placeholder\":\"\",\"help\":\"\",\"name\":\"\",\"is_override\":\"0\",\"is_price\":\"1\"}', '1', '0', '2018-10-11 20:00:00', NULL, NULL),
(12, 0, 'booking', 'item', 'meet_and_greet', 'switch', 1, 0, 0, '{\"label\":\"\",\"placeholder\":\"\",\"help\":\"\",\"name\":\"\",\"is_override\":\"0\",\"is_price\":\"1\"}', '1', '0', '2018-10-11 20:00:00', NULL, NULL),
(13, 0, 'booking', 'item', 'parking', 'number_spin', 1, 0, 0, '{\"label\":\"\",\"placeholder\":\"\",\"help\":\"\",\"name\":\"\",\"is_override\":\"1\",\"is_price\":\"1\",\"trans_key\":\"summary_types.parking\"}', '1', '0', '2018-10-11 20:00:00', NULL, NULL),
(14, 0, 'booking', 'item', 'stopover', 'number_spin', 1, 0, 0, '{\"label\":\"\",\"placeholder\":\"\",\"help\":\"\",\"name\":\"\",\"is_override\":\"1\",\"is_price\":\"1\",\"trans_key\":\"summary_types.stopover\"}', '1', '0', '2018-10-11 20:00:00', NULL, NULL),
(15, 0, 'booking', 'item', 'wheelchair', 'number_spin', 1, 0, 0, '{\"label\":\"\",\"placeholder\":\"\",\"help\":\"\",\"name\":\"\",\"is_override\":\"1\",\"is_price\":\"1\",\"trans_key\":\"summary_types.wheelchair\"}', '1', '0', '2018-10-11 20:00:00', NULL, NULL),
(16, 0, 'booking', 'item', 'other', 'text', 1, 0, 0, '{\"label\":\"\",\"placeholder\":\"\",\"help\":\"\",\"name\":\"\",\"is_override\":\"0\",\"is_price\":\"1\"}', '1', '0', '2018-10-11 20:00:00', NULL, NULL);
